Add example for bad error message
When running `nix flake show`, this outputs:
```
error: 'apps.aarch64-darwin' is not an attribute set
```

Which is really uninformative.